"""Typed interface for the AffineUI Python bindings.

This stub gives editors and type checkers the full public surface of the
``affineui`` package (the compiled ``_affineui`` extension plus the small
Pythonic helpers defined in ``__init__.py``). It mirrors the C++ API: a
declarative View builder layer over a retained HTML/CSS document, plus
strongly-typed component wrappers that degrade gracefully (never crash) when a
widget is missing or of the wrong type.
"""

from __future__ import annotations

from typing import Callable, List, Optional, Sequence, Tuple, overload

__version__: str

def version() -> str: ...
def native_backend() -> str: ...

# affinetools attach — loopback devtools protocol server (discovery/auth
# via <tempdir>/affineui-tools/<pid>.json). No-ops when the native library
# was compiled with AFFINEUI_PERF=0.
def tools_listen(port: int = 0) -> bool: ...
def tools_active() -> bool: ...
def tools_port() -> int: ...
def tools_shutdown() -> None: ...

# ── Enums ───────────────────────────────────────────────────────────────────

class ViewTheme:
    Plain: ViewTheme
    Bootstrap: ViewTheme
    Decius: ViewTheme

class WidgetKind:
    Root: WidgetKind
    Container: WidgetKind
    Text: WidgetKind
    RawHtml: WidgetKind
    Heading: WidgetKind
    Panel: WidgetKind
    Button: WidgetKind
    Checkbox: WidgetKind
    Slider: WidgetKind
    Knob: WidgetKind
    TextInput: WidgetKind
    TextArea: WidgetKind
    Dropdown: WidgetKind
    ButtonGroup: WidgetKind
    VirtualList: WidgetKind
    Card: WidgetKind

class ComponentValidity:
    Valid: ComponentValidity
    WrongType: ComponentValidity
    NotPresent: ComponentValidity

class EventType:
    NoneType: EventType
    MouseMove: EventType
    MouseDown: EventType
    MouseUp: EventType
    MouseWheel: EventType
    KeyDown: EventType
    KeyUp: EventType
    TextInput: EventType
    Resize: EventType
    FocusLost: EventType
    FocusGained: EventType

class MouseButton:
    Left: MouseButton
    Right: MouseButton
    Middle: MouseButton

class Key:
    Unknown: Key
    Escape: Key
    Tab: Key
    Enter: Key
    Backspace: Key
    Delete: Key
    ArrowLeft: Key
    ArrowRight: Key
    ArrowUp: Key
    ArrowDown: Key
    Home: Key
    End: Key
    A: Key; B: Key; C: Key; D: Key; E: Key; F: Key; G: Key; H: Key; I: Key
    J: Key; K: Key; L: Key; M: Key; N: Key; O: Key; P: Key; Q: Key; R: Key
    S: Key; T: Key; U: Key; V: Key; W: Key; X: Key; Y: Key; Z: Key
    Digit0: Key; Digit1: Key; Digit2: Key; Digit3: Key; Digit4: Key
    Digit5: Key; Digit6: Key; Digit7: Key; Digit8: Key; Digit9: Key

# ── Value types ─────────────────────────────────────────────────────────────

class Color:
    r: int
    g: int
    b: int
    a: int
    def __init__(self, r: int, g: int, b: int, a: int = 255) -> None: ...

class Size:
    width: int
    height: int
    def __init__(self, width: int = 0, height: int = 0) -> None: ...

class Point:
    x: int
    y: int
    def __init__(self, x: int = 0, y: int = 0) -> None: ...

class Rect:
    x: int
    y: int
    w: int
    h: int
    def __init__(self, x: int = 0, y: int = 0, w: int = 0, h: int = 0) -> None: ...

class DomHandle:
    def __bool__(self) -> bool: ...

# ── WidgetRef (id-addressed handle; survives refresh, safe when gone) ────────

class WidgetRef:
    def __bool__(self) -> bool: ...
    def valid(self) -> bool: ...
    def id(self) -> int: ...
    def name(self) -> str: ...
    def attr_value(self, name: str, fallback: str = "") -> str: ...
    def text_value(self) -> str: ...
    def has_attr(self, name: str) -> bool: ...
    def named(self, name: str) -> WidgetRef: ...
    def clear(self) -> WidgetRef: ...
    def text(self, text: str) -> WidgetRef: ...
    def attr(self, name: str, value: str) -> WidgetRef: ...
    def remove_attr(self, name: str) -> WidgetRef: ...
    def selector(self, name: str, value: str) -> WidgetRef: ...
    def cls(self, classes: str) -> WidgetRef: ...
    def on_click(self, callback: Callable[[], None]) -> WidgetRef: ...
    def on_change(self, callback: Callable[[str], None]) -> WidgetRef: ...
    def append(self, build: Callable[[View], None]) -> WidgetRef: ...
    def replace(self, build: Callable[[View], None]) -> WidgetRef: ...
    def find_widget(self, name: str) -> WidgetRef: ...

# ── Strongly-typed components ───────────────────────────────────────────────
# Every accessor is safe when the wrapper is not valid(): reads return
# defaults, writes no-op. WrongType wrappers stay attached (you can inspect
# .kind) but typed accessors are inert; generic attr/text/visible still work.

class _Component:
    def __init__(self) -> None: ...
    def __bool__(self) -> bool: ...
    @property
    def valid(self) -> bool: ...
    @property
    def validity(self) -> ComponentValidity: ...
    @property
    def attached(self) -> bool: ...
    @property
    def id(self) -> str: ...
    @property
    def kind(self) -> WidgetKind: ...
    visible: bool
    text: str
    def attr(self, name: str, fallback: str = "") -> str: ...
    def set_attr(self, name: str, value: str) -> None: ...

class Button(_Component):
    label: str
    enabled: bool
    def on_click(self, callback: Callable[[], None]) -> None: ...

class Checkbox(_Component):
    checked: bool
    def on_change(self, callback: Callable[[str], None]) -> None: ...

class TextField(_Component):
    value: str
    def on_change(self, callback: Callable[[str], None]) -> None: ...

class Dropdown(_Component):
    selected: str
    def on_change(self, callback: Callable[[str], None]) -> None: ...

class Slider(_Component):
    def value(self, fallback: float = 0.0) -> float: ...
    def on_change(self, callback: Callable[[str], None]) -> None: ...

class ColorField(_Component):
    color: str
    def on_change(self, callback: Callable[[str], None]) -> None: ...

class DockPanel(_Component):
    active_tab: str

class Foldout(_Component):
    open: bool

# ── Declarative docking (document_view / dockpanel) ─────────────────────────

class Dock:
    Left: Dock
    Right: Dock
    Top: Dock
    Bottom: Dock
    Tab: Dock

class DockCorner:
    TopLeft: DockCorner
    TopRight: DockCorner
    BottomLeft: DockCorner
    BottomRight: DockCorner

class DockHandle:
    id: str
    def __bool__(self) -> bool: ...
    def toolbar(self, build: Callable[[View], None]) -> DockHandle: ...

class DockLocation:
    def __init__(self) -> None: ...
    @staticmethod
    def docked(side: Dock, px: int = 0) -> DockLocation: ...
    @staticmethod
    def tab() -> DockLocation: ...
    @staticmethod
    def floating(anchor: DockCorner, pos: Tuple[int, int],
                 size: Tuple[int, int]) -> DockLocation: ...
    @staticmethod
    def tearoff(anchor: DockCorner, pos: Tuple[int, int],
                size: Tuple[int, int]) -> DockLocation: ...
    def in_(self, panel: DockHandle) -> DockLocation: ...
    def sized(self, px: int) -> DockLocation: ...
    def tearout_size(self, px: Tuple[int, int]) -> DockLocation: ...

class DockPlacement:
    present: bool
    floating: bool
    parent: str
    side: int
    size: int
    x: int
    y: int
    w: int
    h: int
    def __init__(self) -> None: ...

class DockLayout:
    """Opaque dock-arrangement snapshot (Document.dock_layout()); hand it
    back verbatim via View.set_dock_layout_provider."""
    present: bool
    def __init__(self) -> None: ...

# ── VirtualList options ─────────────────────────────────────────────────────

class VirtualListOptions:
    item_count: int
    first_item: int
    visible_items: int
    overscan: int
    item_size: float
    def __init__(self) -> None: ...

# ── View (the declarative component/builder layer) ──────────────────────────

class View:
    def __init__(self, theme: ViewTheme = ...) -> None: ...
    def begin(self) -> None: ...
    def end(self) -> None: ...
    def clear(self) -> None: ...
    def selector(self, name: str, value: str) -> View: ...

    def set_framework_version(self, version: str) -> None: ...
    def framework_version(self) -> str: ...

    # Controls.
    def button(self, label: str, primary: bool = False, key: str = "") -> WidgetRef: ...
    def checkbox(self, label: str, checked: bool, key: str = "") -> WidgetRef: ...
    def toggle(self, label: str, on: bool, key: str = "") -> WidgetRef: ...
    def input(self, label: str, value: str = "", type: str = "text", key: str = "") -> WidgetRef: ...
    def password(self, label: str, value: str = "", key: str = "") -> WidgetRef: ...
    def textarea(self, label: str, value: str = "", rows: int = 3, key: str = "") -> WidgetRef: ...
    def dropdown(self, label: str, options: Sequence[str], selected: str = "", key: str = "") -> WidgetRef: ...
    def button_group(self, label: str, options: Sequence[str], selected: str = "", key: str = "") -> WidgetRef: ...
    def slider(self, label: str, value: float, min: float = 0.0, max: float = 1.0, key: str = "") -> WidgetRef: ...
    def knob(self, label: str, value: float, min: float = 0.0, max: float = 1.0, bipolar: bool = False, key: str = "") -> WidgetRef: ...
    def combo(self, label: str, value: float, step: float = 0.01, key: str = "") -> WidgetRef: ...

    # Generic structure.
    def container(self, classes: str = "", key: str = "", build: Optional[Callable[[View], None]] = ...) -> WidgetRef: ...
    def panel(self, key: str = "", build: Optional[Callable[[View], None]] = ...) -> WidgetRef: ...
    def element(self, tag: str, classes: str = "", key: str = "", build: Optional[Callable[[View], None]] = ...) -> WidgetRef: ...
    def card(self, title: str, classes: str = "", key: str = "", build: Optional[Callable[[View], None]] = ...) -> WidgetRef: ...
    def foldout(self, title: str, expanded: bool = True, key: str = "", build: Optional[Callable[[View], None]] = ...) -> WidgetRef: ...
    def heading(self, level: int, text: str, classes: str = "", key: str = "") -> WidgetRef: ...
    def paragraph(self, text: str, classes: str = "", key: str = "") -> WidgetRef: ...
    def text(self, text: str, key: str = "") -> WidgetRef: ...
    def html(self, markup: str, key: str = "") -> WidgetRef: ...

    # App-shell / structural components.
    def toolbar(self, key: str = "", build: Optional[Callable[[View], None]] = ...) -> WidgetRef: ...
    def toolbar_separator(self, key: str = "") -> WidgetRef: ...
    def icon_button(self, icon: str, key: str = "") -> WidgetRef: ...
    def menu_bar(self, key: str = "", build: Optional[Callable[[View], None]] = ...) -> WidgetRef: ...
    @overload
    def menu_button(self, label: str, menu_id: str, key: str = "") -> WidgetRef: ...
    @overload
    def menu_button(self, label: str, build: Callable[[View], None], key: str = "") -> WidgetRef: ...
    def menu(self, menu_id: str, build: Callable[[View], None]) -> WidgetRef: ...
    def menu_item(self, label: str, icon: str = "", shortcut: str = "", key: str = "") -> WidgetRef: ...
    def menu_item_custom(self, key: str = "", build: Optional[Callable[[View], None]] = ...) -> WidgetRef: ...
    def menu_separator(self, key: str = "") -> WidgetRef: ...
    def submenu(self, label: str, build: Callable[[View], None], icon: str = "", key: str = "") -> WidgetRef: ...
    def menu_brand(self, title: str, icon: str = "", key: str = "") -> WidgetRef: ...
    def menu_spacer(self, key: str = "") -> WidgetRef: ...
    def menu_meta(self, text: str, key: str = "") -> WidgetRef: ...
    def dock_panel(self, title: str, tabpanel_id: str, classes: str = "", key: str = "", build: Optional[Callable[[View], None]] = ...) -> WidgetRef: ...

    # Declarative docking workspace.
    def document_view(self, key: str, build: Callable[[View], None]) -> WidgetRef: ...
    def document(self, content: Callable[[View], None], title: str = "", icon: str = "") -> DockHandle: ...
    def dockpanel(self, title: str, where: DockLocation, content: Callable[[View], None], icon: str = "", key: str = "") -> DockHandle: ...
    def set_dock_layout_provider(self, fn: Callable[[], DockLayout]) -> None: ...
    def set_dock_placement_provider(self, fn: Callable[[str], DockPlacement]) -> None: ...
    def set_dock_size_provider(self, fn: Callable[[str], int]) -> None: ...
    def set_dock_active_tab_provider(self, fn: Callable[[str], str]) -> None: ...

    def splitter(self, horizontal: bool = False, key: str = "") -> WidgetRef: ...
    def tree(self, key: str = "", build: Optional[Callable[[View], None]] = ...) -> WidgetRef: ...
    def tree_row(self, label: str, selected: bool = False, depth: int = 0, key: str = "") -> WidgetRef: ...
    def status_bar(self, key: str = "", build: Optional[Callable[[View], None]] = ...) -> WidgetRef: ...
    def color_field(self, label: str, value: str = "", swatches: Sequence[str] = ..., key: str = "") -> WidgetRef: ...
    def colorfield(self, label: str, value: str = "", key: str = "") -> WidgetRef: ...

    # Query.
    def find_widget(self, name: str) -> WidgetRef: ...
    def button_at(self, name: str) -> Button: ...
    def checkbox_at(self, name: str) -> Checkbox: ...
    def text_field_at(self, name: str) -> TextField: ...
    def dropdown_at(self, name: str) -> Dropdown: ...
    def slider_at(self, name: str) -> Slider: ...
    def color_field_at(self, name: str) -> ColorField: ...
    def dock_panel_at(self, name: str) -> DockPanel: ...
    def foldout_at(self, name: str) -> Foldout: ...

    def to_html_fragment(self) -> str: ...
    def to_html_document(self) -> str: ...

# ── Document / App / events ─────────────────────────────────────────────────

class DispatchResult:
    redraw_requested: bool
    invalidate_view: bool

class HoverInfo:
    valid: bool
    tag: str
    elem_id: str

class Event:
    type: EventType
    pos: Point
    button: MouseButton
    key: Key
    text: str
    shift: bool
    ctrl: bool
    alt: bool
    super: bool
    def __init__(self) -> None: ...

class DocumentScript:
    UiControls: DocumentScript

class Document:
    def __init__(self) -> None: ...
    def set_html(self, html: str) -> None: ...
    def set_user_stylesheet(self, css: str, base_url: Optional[str] = None) -> None: ...
    def hovered_cursor(self) -> int: ...
    def layout(self, width: int, height: int = 0) -> None: ...
    def content_size(self) -> Size: ...
    def set_attribute_by_id(self, elem_id: str, name: str, value: str) -> bool: ...
    def remove_attribute_by_id(self, elem_id: str, name: str) -> bool: ...
    def set_text_by_id(self, elem_id: str, text: str) -> bool: ...
    def weak_handle_for_id(self, elem_id: str) -> DomHandle: ...
    def weak_handle_valid(self, handle: DomHandle) -> bool: ...
    def element(self, elem_id: str) -> ElementRef: ...
    def dock_layout(self) -> DockLayout: ...
    def dock_overrides(self) -> List[Tuple[str, DockPlacement]]: ...
    def take_dock_structure_changed(self) -> bool: ...
    def reset_dock_state(self) -> None: ...

class App:
    def __init__(
        self,
        title: str = "AffineUI",
        width: int = 1024,
        height: int = 768,
        clear_color: Color = ...,
        high_dpi: bool = True,
        vsync: bool = True,
        default_font_family: str = "sans-serif",
        default_font_size: int = 16,
        asset_folders: Sequence[str] = ...,
        perf_overlay: bool = False,
    ) -> None: ...
    def load_html(self, html: str) -> None: ...
    def load_html_file(self, path: str) -> bool: ...
    def load_view(self, view: View) -> None: ...
    def set_stylesheet(self, css: str, base_url: Optional[str] = None) -> None: ...
    def invalidate(self) -> None: ...
    def set_perf_overlay_enabled(self, enabled: bool) -> None: ...
    def perf_overlay_enabled(self) -> bool: ...
    def dispatch(self, event: Event) -> bool: ...
    def quit(self, code: int = 0) -> None: ...
    def window_size(self) -> Size: ...
    def framebuffer_size(self) -> Size: ...
    def dpi_scale(self) -> float: ...
    def frame_telemetry(self) -> dict[str, Any]: ...
    def document(self) -> Document: ...
    def run(self) -> int: ...
    def launch(self, native: bool = True) -> int: ...

class RemotePatchOp:
    CreateElement: RemotePatchOp
    CreateText: RemotePatchOp
    Remove: RemotePatchOp
    SetText: RemotePatchOp
    SetAttribute: RemotePatchOp
    RemoveAttribute: RemotePatchOp

class RemotePatch: ...
class RemotePatchQueue: ...
class PhotoDocument: ...
class PhotoLayerSnapshot: ...

# ── Pythonic helpers defined in __init__.py ─────────────────────────────────

class ElementRef:
    id: str
    def __init__(self, document: Document, elem_id: str) -> None: ...
    def handle(self) -> DomHandle: ...
    def valid(self) -> bool: ...
    def set_attr(self, name: str, value: str) -> bool: ...
    def remove_attr(self, name: str) -> bool: ...
    def set_style(self, css_text: str) -> bool: ...
    def clear_style(self) -> bool: ...
    def set_text(self, text: str) -> bool: ...
    def __bool__(self) -> bool: ...

def element(document: Document, elem_id: str) -> ElementRef: ...
def document(html: str = "", css: str = "", *, width: int = 1024, height: int = 0) -> Document: ...

class bootstrap:
    class selector:
        size: str
        theme: str
    class size:
        sm: str; med: str; medium: str; md: str; lg: str
    class theme:
        light: str; dark: str
    class class_name:
        form: str; props: str; column: str; row: str; note: str
        button_row: str; list: str; list_item: str; tree: str
        tree_row: str; table: str

class decius:
    class selector:
        size: str; style: str; density: str; accent: str; radius: str; dark: str
    class size:
        sm: str; med: str; medium: str; md: str; lg: str
    class style:
        flat: str; three_d: str
    class density:
        compact: str; comfortable: str; spacious: str
    class class_name:
        form: str; props: str; column: str; row: str; note: str
        button_row: str; list: str; list_item: str; tree: str
        tree_row: str; table: str
