# Type stubs for the photo_core example-support extension module.
#
# photo_core is NOT part of the affineui library — it is the raster core
# behind the Decius Photo Edit sample (examples/core/photoedit), built as
# its own pybind11 module and imported alongside affineui.
from typing import Optional

from affineui import App

class PhotoLayer:
    id: int
    name: str
    kind: str
    blend: str
    visible: bool
    locked: bool
    opacity: float
    fill: float

class PhotoHistoryEntry:
    name: str
    icon: str

class PhotoDocument:
    def __init__(self, width: int = 1280, height: int = 800) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def new_document(self, width: int, height: int,
                     background_hex: str = "") -> None: ...
    def load_sample_scene(self) -> None: ...
    def zoom(self) -> float: ...
    def pan_x(self) -> float: ...
    def pan_y(self) -> float: ...
    def set_pan(self, px: float, py: float) -> None: ...
    def set_zoom(self, zoom: float) -> None: ...
    def set_zoom_at(self, zoom: float, client_x: float,
                    client_y: float) -> None: ...
    def fit_to_screen(self) -> None: ...
    def stage_rect(self) -> Optional[tuple[int, int, int, int]]: ...
    def screen_to_doc(self, client_x: float,
                      client_y: float) -> tuple[float, float]: ...
    def doc_origin(self) -> tuple[float, float]: ...
    def layers(self) -> list[PhotoLayer]: ...
    def active_layer(self) -> PhotoLayer: ...
    def active_index(self) -> int: ...
    def active_id(self) -> int: ...
    def set_active_index(self, index: int) -> bool: ...
    def set_active_id(self, id: int) -> bool: ...
    def add_layer(self, name: str = "", blend: str = "source-over",
                  opacity: float = 1.0, label: str = "New Layer",
                  icon: str = "plus") -> int: ...
    def duplicate_active(self) -> bool: ...
    def delete_active(self) -> bool: ...
    def move_active(self, dir: int) -> bool: ...
    def reorder_layer(self, id: int, new_index: int) -> bool: ...
    def rename_layer(self, id: int, name: str) -> bool: ...
    def toggle_visible(self, id: int) -> bool: ...
    def set_active_opacity(self, value: float) -> bool: ...
    def set_active_fill(self, value: float) -> bool: ...
    def set_active_blend(self, blend: str) -> bool: ...
    def set_active_locked(self, locked: bool) -> bool: ...
    def merge_down(self) -> bool: ...
    def flatten(self) -> bool: ...
    def set_selection(self, x: int, y: int, w: int, h: int) -> None: ...
    def clear_selection(self) -> None: ...
    def has_selection(self) -> bool: ...
    def selection(self) -> Optional[tuple[int, int, int, int]]: ...
    def select_all(self) -> None: ...
    def delete_selection_pixels(self) -> bool: ...
    def begin_stroke(self, tool: str, x: float, y: float,
                     size: float = 24.0, hardness: float = 0.7,
                     opacity: float = 1.0, flow: float = 1.0,
                     color: str = "#000000") -> bool: ...
    def stroke_to(self, x: float, y: float) -> None: ...
    def end_stroke(self) -> None: ...
    def cancel_stroke(self) -> None: ...
    def stroking(self) -> bool: ...
    def set_clone_source(self, x: float, y: float) -> None: ...
    def has_clone_source(self) -> bool: ...
    def begin_move(self) -> bool: ...
    def move_to(self, dx: float, dy: float) -> None: ...
    def end_move(self) -> None: ...
    def fill_at(self, x: float, y: float, color: str,
                tolerance: float = 32.0, contiguous: bool = True,
                opacity: float = 1.0) -> bool: ...
    def wand_select(self, x: float, y: float, tolerance: float = 32.0,
                    contiguous: bool = True
                    ) -> Optional[tuple[int, int, int, int]]: ...
    def pick_color(self, x: float, y: float) -> str: ...
    def apply_gradient(self, x0: float, y0: float, x1: float, y1: float,
                       color: str, opacity: float = 1.0) -> bool: ...
    def place_type(self, x: float, y: float, text: str, size: float = 64.0,
                   color: str = "#000000", bold: bool = True) -> int: ...
    def draw_shape(self, x0: float, y0: float, x1: float, y1: float,
                   color: str, radius: float = 0.0) -> bool: ...
    def pen_add_point(self, x: float, y: float) -> None: ...
    def pen_clear(self) -> None: ...
    def pen_count(self) -> int: ...
    def fill_layer(self, color: str, opacity: float = 1.0,
                   blend: str = "source-over",
                   label: str = "Fill") -> bool: ...
    def stroke_selection(self, color: str, width: float = 4.0,
                         location: str = "center",
                         opacity: float = 1.0) -> bool: ...
    def apply_crop(self) -> bool: ...
    def crop_to(self, x: int, y: int, w: int, h: int) -> bool: ...
    def resize_image(self, w: int, h: int) -> bool: ...
    def resize_canvas(self, w: int, h: int, anchor: str = "mc") -> bool: ...
    def begin_preview(self) -> bool: ...
    def preview_adjust(self, kind: str, a: float = 0.0, b: float = 0.0,
                       c: float = 0.0) -> None: ...
    def commit_preview(self, label: str = "Adjustment",
                       icon: str = "color-grade") -> None: ...
    def cancel_preview(self) -> None: ...
    def previewing(self) -> bool: ...
    def apply_adjust(self, kind: str, a: float = 0.0, label: str = "",
                     icon: str = "") -> bool: ...
    def place_asset(self, asset: str) -> int: ...
    def history_entries(self) -> list[PhotoHistoryEntry]: ...
    def history_index(self) -> int: ...
    def history_source(self) -> int: ...
    def set_history_source(self, index: int) -> None: ...
    def snapshot(self, name: str, icon: str = "") -> None: ...
    def undo(self) -> str: ...
    def redo(self) -> str: ...
    def jump_to(self, index: int) -> bool: ...
    def export_png(self, path: str, scale: float = 1.0,
                   opaque_white: bool = False) -> bool: ...
    def attach(self, app: App) -> None: ...
    def detach(self) -> None: ...
    def request_repaint(self) -> None: ...
    def thumb_paint_name(self, layer_id: int) -> str: ...
    def revision(self) -> int: ...
