#!/usr/bin/env python3
"""Embed the Decius CSS + icon font into a C header for compile-time bundling.

Reads a hand-picked set of assets from `examples/frameworks/{css,fonts}/`,
zlib-compresses each one, and emits a header with byte arrays plus a small
table of entries. The C++ core includes this header when built with
-DAFFINEUI_BUNDLE_DECIUS=ON (the default for the shared library and the
Python/Rust/C# bindings), and its resource-loader hook serves any URL that
starts with `frameworks/` out of these bytes.

Compression: zlib format. Deflated bytes are decoded via `stbi_zlib_decode_
buffer` (already vendored in stb_image.h — no new dependency).

Usage:
    python3 tools/embed_decius.py <output-header-path>

The header is deterministic given the inputs, so cmake can re-run it as a
generated dependency without incremental-build drift.
"""

from __future__ import annotations

import argparse
import sys
import textwrap
import zlib
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FRAMEWORKS = REPO_ROOT / "examples" / "frameworks"


@dataclass(frozen=True)
class BundledAsset:
    # URL the CSS resolves via `url(...)` — same tail path as the on-disk
    # location under examples/frameworks/. This is the key the resource-
    # loader hook matches at runtime.
    url_suffix: str
    disk_path: Path


# Minimum working set — CSS + one TTF per family. The engine's font
# stack (fontstash + stb_truetype) parses TTF/OTF only; woff/woff2 are
# skipped because we'd need a brotli/zlib unwrapper on top. TTF versions
# ship only for `decius-icons` today — body/mono fonts fall back to the
# host OS's default sans/mono, which is fine for MVP.
ASSETS: list[BundledAsset] = [
    BundledAsset(
        url_suffix="frameworks/css/decius-css-0.6.2.bundle.min.css",
        disk_path=FRAMEWORKS / "css" / "decius-css-0.6.2.bundle.min.css",
    ),
    # Icon font — the interactive glyphs (menu chevrons, close buttons,
    # tree carets, etc.) that Decius uses everywhere. Without this,
    # widgets have empty squares where icons should be.
    BundledAsset(
        url_suffix="frameworks/fonts/decius-icons.ttf",
        disk_path=FRAMEWORKS / "fonts" / "decius-icons.ttf",
    ),
]


def format_byte_array(name: str, data: bytes) -> str:
    """Emit a C `static const unsigned char name[] = { ... };` literal.

    Wraps at ~16 bytes per line for reasonable diff / grep-ability.
    """
    lines = ["static const unsigned char " + name + "[] = {"]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def slug(url_suffix: str) -> str:
    """Turn a URL suffix into a C-identifier fragment."""
    return (
        url_suffix.replace("/", "_")
        .replace("-", "_")
        .replace(".", "_")
        .upper()
    )


def build_header() -> str:
    entries: list[tuple[BundledAsset, bytes]] = []
    for asset in ASSETS:
        raw = asset.disk_path.read_bytes()
        # zlib.compress emits zlib-format (RFC 1950); stbi_zlib_decode_buffer
        # decodes exactly that format.
        packed = zlib.compress(raw, level=9)
        entries.append((asset, packed))

    header: list[str] = []
    header.append("// AUTO-GENERATED by tools/embed_decius.py — do NOT edit by hand.")
    header.append("// Compile-time bundle of the Decius CSS framework + its icon font.")
    header.append("// Regenerate whenever the source files under examples/frameworks/")
    header.append("// change (cmake handles this via a generator dependency).")
    header.append("")
    header.append("#pragma once")
    header.append("")
    header.append("#include <stddef.h>")
    header.append("")
    header.append("namespace affineui::decius {")
    header.append("")

    for asset, packed in entries:
        slug_name = slug(asset.url_suffix)
        original_size = asset.disk_path.stat().st_size
        header.append(f"// {asset.url_suffix}  ({original_size} bytes → {len(packed)} zlib)")
        header.append(format_byte_array(f"{slug_name}_ZLIB", packed))
        header.append(f"static const size_t   {slug_name}_ZLIB_LEN = {len(packed)};")
        header.append(f"static const size_t   {slug_name}_RAW_LEN  = {original_size};")
        header.append("")

    # Manifest: an array of (url, zlib-bytes-ptr, zlib-len, raw-len) tuples
    # so the runtime resource-loader hook can iterate to find a match.
    header.append("struct BundledAsset {")
    header.append("    const char*         url_suffix;   // e.g. \"frameworks/css/decius.css\"")
    header.append("    const unsigned char* zlib_bytes;  // zlib-compressed payload")
    header.append("    size_t              zlib_len;")
    header.append("    size_t              raw_len;      // decompressed size, for buffer allocation")
    header.append("};")
    header.append("")
    header.append(f"static const BundledAsset ASSETS[] = {{")
    for asset, _ in entries:
        slug_name = slug(asset.url_suffix)
        header.append(
            f"    {{ \"{asset.url_suffix}\", {slug_name}_ZLIB, {slug_name}_ZLIB_LEN, {slug_name}_RAW_LEN }},"
        )
    header.append("};")
    header.append(f"static const size_t ASSET_COUNT = {len(entries)};")
    header.append("")
    header.append("}  // namespace affineui::decius")
    header.append("")

    total_zlib = sum(len(z) for _, z in entries)
    total_raw = sum(a.disk_path.stat().st_size for a, _ in entries)
    print(
        f"embed_decius: {len(entries)} asset(s), {total_raw:,} raw bytes → {total_zlib:,} zlib-compressed",
        file=sys.stderr,
    )

    return "\n".join(header)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path, help="Path to write the generated .h.")
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_header(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
